name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'CollabBackend'
        format: 'HTML'
        args: >
          --scan CollabBackend
          --suppression .github/suppressions.xml
          --failOnCVSS 7
          --enableRetired

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: Dependency Check Report
        path: reports 